### ISSUE TITLE
[meta] Wide review tracker

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp-lifecycle#11]
As a requirement for [transitioning to Candidate Recommendation](https://www.w3.org/2020/Process-20200915/#transition-cr) the group:

> *MUST* show that the specification has received wide review

To satisfy this requirement, we can use this tracker issue as evidence that [wide review] from horizontal groups has been received.

  * Technical Architecture Group
    * [x] Review request: https://github.com/w3ctag/design-reviews/issues/523
    * [ ] Feedback:
    * [ ] Resolution:
  * Security
    * [x] Review request: https://github.com/w3c/security-request/issues/33
    * [x] Feedback: N/A
    * [x] Resolution: time out
  * Privacy
    * [x] Review request: https://github.com/w3cping/privacy-request/issues/93
    * [x] Feedback: https://github.com/w3cping/privacy-request/issues/93#issuecomment-1209999758
    * [ ] Resolution:
  * Internationalization
    * [x] Review request: https://github.com/w3c/i18n-request/issues/180
    * [x] Feedback: "All issues are closed."
    * [x] Resolution: https://github.com/w3c/miniapp-lifecycle/issues?q=is%3Aissue+is%3Aclosed+label%3Ai18n-needs-resolution
  * Accessibility
    * [x] Review request: https://github.com/w3c/a11y-request/issues/27
    * [x] Feedback: "Review complete with no comments."
    * [x] Resolution: N/A

[wide review]: https://www.w3.org/2020/Process-20200915/#dfn-wide-review

**Comment by xfq** [comment]
When we are ready, I can start requesting reviews.

**Comment by xfq** [comment]
Blockers:

* https://github.com/w3c/miniapp-lifecycle/issues/13
* https://github.com/w3c/miniapp-lifecycle/issues/27
